# Generated by Django 5.2.1 on 2025-06-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('received', 'Order Received'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', help_text='Current status of the order', max_length=20)),
            ],
        ),
    ]
